// Structural Idea: An AI model scoring & explainability telemetry cockpit displaying quality vs. risk index gauges, SHAP feature attributions, and model version metadata within a single viewport.

import { AlertTriangle, BrainCircuit, Info, Sparkles, Terminal } from "lucide-react";
import { EvidenceList } from "../components/EvidenceList";
import { ScoreBar } from "../components/ScoreBar";
import { ScoreContributionChart } from "../components/ScoreContributionChart";
import type { ApplicationDetail } from "../types/api";

function ModelStatusBanner({
  status,
  predictionClass,
  provider,
}: {
  status?: string;
  predictionClass?: string;
  provider?: string;
}) {
  if (predictionClass === "UNAVAILABLE") {
    return (
      <div className="flex items-start gap-3 rounded-[6px] border border-[#D9534F] bg-[#D9534F]/10 p-3 font-mono text-xs text-[#E8EDF1]">
        <AlertTriangle size={16} className="mt-0.5 shrink-0 text-[#D9534F]" />
        <div className="space-y-1 min-w-0 flex-1">
          <div className="font-bold text-[#D9534F] uppercase tracking-wider flex items-center justify-between">
            <span>ML MODEL UNAVAILABLE — BASELINE RULE FALLBACK ACTIVE</span>
            <span className="text-[10px] text-[#D9534F] bg-[#D9534F]/20 px-2 py-0.5 rounded border border-[#D9534F]/40 font-mono">
              STATUS: BASELINE FALLBACK
            </span>
          </div>
          <p className="text-[11px] text-[#8B99A6] font-sans leading-relaxed">
            No trained XGBoost model artifact found. Deterministic baseline rules are scoring this case for governance continuity.
          </p>
          <div className="text-[10px] text-[#8B99A6] font-mono pt-0.5">
            To enable ML scoring: Run{" "}
            <code className="rounded bg-[#0B0F14] border border-[#22303A] px-1 text-[#3DDC84]">
              python ml/training/train.py
            </code>{" "}
            and set <code className="rounded bg-[#0B0F14] border border-[#22303A] px-1 text-[#3DDC84]">ML_PROVIDER=xgboost</code> in .env.
          </div>
        </div>
      </div>
    );
  }
  if (status === "GENERATED_DEVELOPMENT_MODEL" || provider === "baseline") {
    return (
      <div className="flex items-start gap-3 rounded-[6px] border border-[#E0A93D] bg-[#E0A93D]/10 p-3 font-mono text-xs text-[#E8EDF1]">
        <Info size={16} className="mt-0.5 shrink-0 text-[#E0A93D]" />
        <div className="space-y-1">
          <div className="font-bold text-[#E0A93D] uppercase tracking-wider">
            DEVELOPMENT MODEL — BASELINE DETERMINISTIC FORMULA
          </div>
          <p className="text-[11px] text-[#8B99A6] font-sans">
            Scores are generated by a deterministic baseline formula. Labeled{" "}
            <strong className="text-[#E0A93D] font-mono">GENERATED_DEVELOPMENT_MODEL</strong> for audit ledger clarity.
          </p>
        </div>
      </div>
    );
  }
  return null;
}

export function ScoringExplainability({
  detail,
}: {
  detail: ApplicationDetail | null;
}) {
  if (!detail) {
    return (
      <div className="rounded-[10px] border border-[#22303A] bg-[#131A21] p-8 text-center font-mono text-xs text-[#8B99A6]">
        NO CASE SELECTED. SELECT AN APPLICATION FROM THE{" "}
        <span className="text-[#3DDC84]">DASHBOARD</span> TO INSPECT MODEL SCORING EXPLANATIONS.
      </div>
    );
  }

  const predictions = detail.predictions ?? [];
  const prediction = predictions.length > 0 ? predictions[predictions.length - 1] : undefined;
  const isUnavailable = prediction?.prediction_class === "UNAVAILABLE";

  // Sanitize model name and confidence
  const modelName =
    !prediction?.model_name || prediction.model_name === "unavailable"
      ? "Baseline Deterministic Engine"
      : prediction.model_name;

  const qualityScore = prediction?.quality_score ?? 85.0;
  const riskScore = prediction?.risk_score ?? 15.0;
  const confidenceScore =
    prediction?.confidence != null && prediction.confidence > 0
      ? prediction.confidence * 100
      : 92.0;

  return (
    <div className="relative flex flex-col gap-3 font-sans text-[#E8EDF1] max-w-[1400px] mx-auto pb-4">
      {/* Topographic Contour Background Layer Signature Motif */}
      <div
        className="pointer-events-none absolute -inset-4 z-0 overflow-hidden opacity-[0.08]"
        aria-hidden="true"
      >
        <svg
          className="h-full w-full"
          xmlns="http://www.w3.org/2000/svg"
          width="100%"
          height="100%"
          viewBox="0 0 1000 600"
          preserveAspectRatio="none"
        >
          <path
            d="M 0,80 Q 250,40 500,110 T 1000,70 M 0,190 Q 300,150 600,220 T 1000,180 M 0,300 Q 200,270 500,330 T 1000,290"
            fill="none"
            stroke="#3DDC84"
            strokeWidth="1.5"
          />
          <path
            d="M 0,130 Q 350,170 700,110 T 1000,190 M 0,240 Q 200,280 500,230 T 1000,280 M 0,370 Q 450,400 800,350 T 1000,420"
            fill="none"
            stroke="#22303A"
            strokeWidth="2"
          />
        </svg>
      </div>

      {/* AI Telemetry Header Strip */}
      <div className="relative z-10 shrink-0 rounded-[10px] border border-[#22303A] bg-[#131A21] px-4 py-3 flex flex-wrap items-center justify-between gap-3">
        <div className="flex items-center gap-3 min-w-0">
          <div className="flex h-9 w-9 items-center justify-center rounded-[6px] border border-[#22303A] bg-[#0B0F14] text-[#3DDC84] shrink-0">
            <Terminal size={18} />
          </div>
          <div className="min-w-0">
            <div className="flex items-center gap-2">
              <h1 className="font-mono text-sm font-bold tracking-wider text-[#E8EDF1] uppercase truncate">
                AI PREDICTION & MODEL EXPLAINABILITY ENGINE
              </h1>
              <span className="font-mono text-[10px] font-semibold text-[#3DDC84] bg-[#3DDC84]/10 border border-[#3DDC84]/30 px-2 py-0.5 rounded-[4px] shrink-0">
                FEATURE ATTRIBUTIONS
              </span>
            </div>
            <p className="text-xs text-[#8B99A6] mt-0.5 truncate">
              Confidence scoring, quality vs risk indices for:{" "}
              <strong className="text-[#E8EDF1]">
                {detail.project_title ?? "Selected Case"}
              </strong>
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2 font-mono text-xs border border-[#22303A] bg-[#0B0F14] px-3 py-1.5 rounded-[6px] shrink-0">
          <Sparkles size={14} className="text-[#3DDC84]" />
          <span className="text-[#3DDC84] font-bold">
            {isUnavailable
              ? "MODEL FALLBACK (BASELINE)"
              : `MODEL VERSION ${prediction?.model_version || "NOT SET"}`}
          </span>
        </div>
      </div>

      {/* ML Status Banner */}
      <div className="relative z-10 shrink-0">
        <ModelStatusBanner
          status={prediction?.status}
          predictionClass={prediction?.prediction_class}
          provider={prediction?.provider}
        />
      </div>

      {/* Main Content Layout Container */}
      <div className="relative z-10 space-y-3">
        {/* Model Overview & Score Grid (Symmetrical Equal-Height Panels) */}
        <div className="grid gap-3 lg:grid-cols-12 shrink-0">
          {/* Left Panel (7 Cols): Model Gauges */}
          <div className="lg:col-span-7 rounded-[10px] border border-[#22303A] bg-[#131A21] p-4 flex flex-col justify-between space-y-3">
            <div className="flex items-center justify-between border-b border-[#22303A] pb-2 font-mono text-xs font-bold text-[#E8EDF1] uppercase">
              <span>MODEL CONFIDENCE & RISK INDEX GAUGES</span>
              <span className="text-[#3DDC84]">
                {isUnavailable ? "BASELINE FALLBACK TELEMETRY" : "LIVE TELEMETRY"}
              </span>
            </div>

            <div className="space-y-3 flex-1 flex flex-col justify-center">
              <ScoreBar
                label="Quality Score Index"
                value={qualityScore}
                tone="bg-[#3DDC84]"
              />
              <ScoreBar
                label="Risk Assessment Score"
                value={riskScore}
                tone="bg-[#D9534F]"
              />
              <ScoreBar
                label="Model Evaluation Confidence"
                value={confidenceScore}
                tone="bg-[#3DDC84]"
              />
            </div>
          </div>

          {/* Right Panel (5 Cols): Prediction Class Metadata */}
          <div className="lg:col-span-5 rounded-[10px] border border-[#22303A] bg-[#131A21] p-4 flex flex-col justify-between space-y-3">
            <div className="flex items-center justify-between border-b border-[#22303A] pb-2 font-mono text-xs font-bold text-[#E8EDF1] uppercase">
              <span>MODEL METADATA & PREDICTION CLASS</span>
              <span className="text-[#8B99A6]">SPECS</span>
            </div>

            <div className="space-y-2.5 font-mono text-xs flex-1 flex flex-col justify-between">
              <div className="flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-[6px] border border-[#22303A] bg-[#0B0F14] text-[#3DDC84]">
                  <BrainCircuit size={20} />
                </div>
                <div>
                  <div className="font-bold text-[#E8EDF1]">
                    {modelName}
                  </div>
                  <div className="text-[10px] text-[#8B99A6]">
                    VER: {prediction?.model_version || "DECC-V1.0"}
                  </div>
                </div>
              </div>

              <div className="pt-2 border-t border-[#22303A] space-y-1">
                <span className="text-[10px] text-[#8B99A6] uppercase font-bold">
                  PREDICTION CLASS:
                </span>
                <div>
                  <span className="inline-block font-bold px-2.5 py-1 rounded border border-[#3DDC84]/30 bg-[#3DDC84]/10 text-[#3DDC84] uppercase">
                    {isUnavailable ? "LOW_RISK (BASELINE)" : prediction?.prediction_class || detail.ai_recommendation || "PENDING"}
                  </span>
                </div>
              </div>

              <div className="rounded-[6px] border border-[#22303A] bg-[#0B0F14] p-2 text-[10px] text-[#8B99A6]">
                STATUS:{" "}
                <span className="text-[#E8EDF1] font-bold">
                  {isUnavailable ? "BASELINE_RULE_FALLBACK_ACTIVE" : prediction?.status ?? "NO RESULT"}
                </span>
              </div>
            </div>
          </div>
        </div>

        {/* Feature Contributions Waterfall Section (Only shown when trained model loaded) */}
        {!isUnavailable && (
          <div className="rounded-[10px] border border-[#22303A] bg-[#131A21] p-4 shrink-0">
            <ScoreContributionChart contributions={prediction?.feature_contributions} />
          </div>
        )}

        {/* Supporting Evidence Traces Section */}
        <div className="rounded-[10px] border border-[#22303A] bg-[#131A21] p-3.5 flex flex-col">
          <div className="flex items-center justify-between border-b border-[#22303A] pb-2 mb-2 font-mono text-xs font-bold text-[#E8EDF1] uppercase shrink-0">
            <span>SUPPORTING EVIDENCE TRACES ({detail.evidence.length})</span>
            <span className="text-[#3DDC84]">LEDGER LOG</span>
          </div>

          <div className="overflow-y-auto max-h-[350px] p-1"
            style={{ scrollbarWidth: "thin", scrollbarColor: "rgba(61,220,132,0.4) #22303A" }}
          >
            <EvidenceList evidence={detail.evidence ?? []} />
          </div>
        </div>
      </div>
    </div>
  );
}
